---
- name: Copy K3s service file
  register: k3s_service
  ansible.builtin.template:
    src: "master_k3s.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: '0644'

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    enabled: true

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  ansible.builtin.stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  ansible.builtin.slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  ansible.builtin.set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  ansible.builtin.file:
    path: ~{{ ansible_user_id }}/.kube
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "u=rwx,g=rx,o="

- name: Change k3s.yaml permissions to 644
  ansible.builtin.file:
    path: /etc/rancher/k3s/k3s.yaml
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'

- name: Print master
  ansible.builtin.debug:
    msg: "{{ k3s_master_ip }}"

- name: Replace https://localhost:6443 by https://k3s_master-ip:6443
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_master_ip }}:6443
      --kubeconfig ~{{ ansible_user_id }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: copy config to local host
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: true
  when: k3s_copy_kubeconfig
