---
- name: Copy K3s service file
  ansible.builtin.template:
    src: "node_k3s.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: '0755'

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: k3s-node
    state: restarted
    enabled: true
