---
k3s_version: v1.28.3+k3s2
k3s_systemd_dir: /etc/systemd/system
k3s_master_ip: "{{ lookup('dig', hostvars[groups['k3s_master'][0]]['ansible_host'] | default(groups['k3s_master'][0])) }}"
k3s_extra_server_args: "--write-kubeconfig-mode=644"
k3s_extra_agent_args: ""
k3s_copy_kubeconfig: true
k3s_metallb: true
k3s_metallb_version: "v0.13.1"
k3s_metallb_range: "10.10.1.1-10.10.1.3"
k3s_argocd: true
k3s_argocd_service_type: LoadBalancer
k3s_dns_servers: ['10.10.0.1', '192.168.1.1']
k3s_longhorn: true
k3s_longhorn_version: "v1.5.3"
k3s_traefik_dev: true
k3s_mkcert: true
k3s_domain: ".lab"
