pvesm_local_storage_path: /var/lib/vz
pvesm_local_storage_iso_subpath: template/iso

iso_images_to_download:
  - filename: debian-12-generic-amd64.qcow2
    url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
    is_cloud_init_image: true
    cloud_init_vm_id: "{{ debian_vm_id }}"
    cloud_init_vm_instance_template_name: debian-12-generic-amd64
    enable_qemu_guest_agent: true
    bridge: vlan
